
stages:
  - build
  - test
  - release
  - deploy

build:
  image: gitlab/dind # тут нормально работает docker login, но не работает apk
  services:
    - docker:dind
  before_script:
    - docker login -u $HUB_USERNAME -p $HUB_TOKEN
  stage: build
  script:
    - docker build -t agapochkina/private_registry:django .
    - docker push agapochkina/private_registry:django
  tags:
    - docker
  only:
    changes:
      - Dockerfile
      - ./djangogirls/*

deploy:
  image: docker:latest # тут нормально работает apk, но не работает docker login
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://192.168.56.105:2375 # костыль для docker login
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - docker login -u $HUB_USERNAME -p $HUB_TOKEN
  script:
    - ssh -o StrictHostKeyChecking=no gitlab-runner@192.168.56.103 "cd /opt/deploy/django-docker && docker-compose up -d"
  tags:
    - docker
