version: '3.8'

services:
  django:
    image: registry.gitlab.com/agapochkina/django-docker
    container_name: django 
    volumes: 
      - './djangogirls:/opt/djangogirls'
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    links:
      - "db:postgres"
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
