version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
     - /opt/deploy/jenkins-deploy/nginx.conf:/etc/nginx/conf.d
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.56.102:12201
        tag: nginx-logs

  django:
    image: ${TAG}
    container_name: django 
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:postgres
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.56.102:12201
        tag: django-logs
    command: >
      sh -c "npm install && gulp watch &
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres
    container_name: postgres
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.56.102:12201
        tag: postgres-logs
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
