version: '3.8'

services:
  django:
    image: agapochkina/private_registry:django-${TAG}
    container_name: django 
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:postgres
    command: >
      sh -c "npm install && gulp watch &
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
